// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/setup/proto/auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthOptions struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AllowUnauthenticated bool                   `protobuf:"varint,1,opt,name=allow_unauthenticated,json=allowUnauthenticated,proto3" json:"allow_unauthenticated,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AuthOptions) Reset() {
	*x = AuthOptions{}
	mi := &file_pkg_setup_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthOptions) ProtoMessage() {}

func (x *AuthOptions) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_setup_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthOptions.ProtoReflect.Descriptor instead.
func (*AuthOptions) Descriptor() ([]byte, []int) {
	return file_pkg_setup_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthOptions) GetAllowUnauthenticated() bool {
	if x != nil {
		return x.AllowUnauthenticated
	}
	return false
}

var file_pkg_setup_proto_auth_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*AuthOptions)(nil),
		Field:         53040,
		Name:          "pkg.setup.auth_options",
		Tag:           "bytes,53040,opt,name=auth_options",
		Filename:      "pkg/setup/proto/auth.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional pkg.setup.AuthOptions auth_options = 53040;
	E_AuthOptions = &file_pkg_setup_proto_auth_proto_extTypes[0]
)

var File_pkg_setup_proto_auth_proto protoreflect.FileDescriptor

const file_pkg_setup_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/setup/proto/auth.proto\x12\tpkg.setup\x1a google/protobuf/descriptor.proto\"B\n" +
	"\vAuthOptions\x123\n" +
	"\x15allow_unauthenticated\x18\x01 \x01(\bR\x14allowUnauthenticated:c\n" +
	"\fauth_options\x12\x1e.google.protobuf.MethodOptions\x18\xb0\x9e\x03 \x01(\v2\x16.pkg.setup.AuthOptionsB\x03\x88\x01\x01R\vauthOptions\x88\x01\x01B.Z,github.com/cfhn/our-space/pkg/setup/proto;pbb\x06proto3"

var (
	file_pkg_setup_proto_auth_proto_rawDescOnce sync.Once
	file_pkg_setup_proto_auth_proto_rawDescData []byte
)

func file_pkg_setup_proto_auth_proto_rawDescGZIP() []byte {
	file_pkg_setup_proto_auth_proto_rawDescOnce.Do(func() {
		file_pkg_setup_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_setup_proto_auth_proto_rawDesc), len(file_pkg_setup_proto_auth_proto_rawDesc)))
	})
	return file_pkg_setup_proto_auth_proto_rawDescData
}

var file_pkg_setup_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_setup_proto_auth_proto_goTypes = []any{
	(*AuthOptions)(nil),                // 0: pkg.setup.AuthOptions
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_pkg_setup_proto_auth_proto_depIdxs = []int32{
	1, // 0: pkg.setup.auth_options:extendee -> google.protobuf.MethodOptions
	0, // 1: pkg.setup.auth_options:type_name -> pkg.setup.AuthOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_setup_proto_auth_proto_init() }
func file_pkg_setup_proto_auth_proto_init() {
	if File_pkg_setup_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_setup_proto_auth_proto_rawDesc), len(file_pkg_setup_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_pkg_setup_proto_auth_proto_goTypes,
		DependencyIndexes: file_pkg_setup_proto_auth_proto_depIdxs,
		MessageInfos:      file_pkg_setup_proto_auth_proto_msgTypes,
		ExtensionInfos:    file_pkg_setup_proto_auth_proto_extTypes,
	}.Build()
	File_pkg_setup_proto_auth_proto = out.File
	file_pkg_setup_proto_auth_proto_goTypes = nil
	file_pkg_setup_proto_auth_proto_depIdxs = nil
}
