// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: ourspace-firmware/proto/api.proto

package pb

import (
	proto "github.com/cfhn/our-space/ourspace-backend/proto"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardSerial    string                 `protobuf:"bytes,1,opt,name=card_serial,proto3" json:"card_serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanCardRequest) Reset() {
	*x = ScanCardRequest{}
	mi := &file_ourspace_firmware_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanCardRequest) ProtoMessage() {}

func (x *ScanCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ourspace_firmware_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanCardRequest.ProtoReflect.Descriptor instead.
func (*ScanCardRequest) Descriptor() ([]byte, []int) {
	return file_ourspace_firmware_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *ScanCardRequest) GetCardSerial() string {
	if x != nil {
		return x.CardSerial
	}
	return ""
}

type ScanCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcome       string                 `protobuf:"bytes,1,opt,name=outcome,proto3" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanCardResponse) Reset() {
	*x = ScanCardResponse{}
	mi := &file_ourspace_firmware_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanCardResponse) ProtoMessage() {}

func (x *ScanCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ourspace_firmware_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanCardResponse.ProtoReflect.Descriptor instead.
func (*ScanCardResponse) Descriptor() ([]byte, []int) {
	return file_ourspace_firmware_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *ScanCardResponse) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

type ListenForCardEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenForCardEventsRequest) Reset() {
	*x = ListenForCardEventsRequest{}
	mi := &file_ourspace_firmware_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenForCardEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenForCardEventsRequest) ProtoMessage() {}

func (x *ListenForCardEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ourspace_firmware_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenForCardEventsRequest.ProtoReflect.Descriptor instead.
func (*ListenForCardEventsRequest) Descriptor() ([]byte, []int) {
	return file_ourspace_firmware_proto_api_proto_rawDescGZIP(), []int{2}
}

type ListenForCardEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Card          *Card                  `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
	Member        *Member                `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
	Presence      *proto.Presence        `protobuf:"bytes,4,opt,name=presence,proto3" json:"presence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenForCardEventsResponse) Reset() {
	*x = ListenForCardEventsResponse{}
	mi := &file_ourspace_firmware_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenForCardEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenForCardEventsResponse) ProtoMessage() {}

func (x *ListenForCardEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ourspace_firmware_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenForCardEventsResponse.ProtoReflect.Descriptor instead.
func (*ListenForCardEventsResponse) Descriptor() ([]byte, []int) {
	return file_ourspace_firmware_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *ListenForCardEventsResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ListenForCardEventsResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *ListenForCardEventsResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *ListenForCardEventsResponse) GetPresence() *proto.Presence {
	if x != nil {
		return x.Presence
	}
	return nil
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_ourspace_firmware_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_ourspace_firmware_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_ourspace_firmware_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ValidFrom     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=valid_from,proto3" json:"valid_from,omitempty"`
	ValidTo       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=valid_to,proto3" json:"valid_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_ourspace_firmware_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_ourspace_firmware_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_ourspace_firmware_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *Card) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

type LocalPresence struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Presence       *proto.Presence        `protobuf:"bytes,1,opt,name=presence,proto3" json:"presence,omitempty"`
	SynchronizedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=synchronized_at,json=synchronizedAt,proto3" json:"synchronized_at,omitempty"`
	ModifiedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocalPresence) Reset() {
	*x = LocalPresence{}
	mi := &file_ourspace_firmware_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalPresence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalPresence) ProtoMessage() {}

func (x *LocalPresence) ProtoReflect() protoreflect.Message {
	mi := &file_ourspace_firmware_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalPresence.ProtoReflect.Descriptor instead.
func (*LocalPresence) Descriptor() ([]byte, []int) {
	return file_ourspace_firmware_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *LocalPresence) GetPresence() *proto.Presence {
	if x != nil {
		return x.Presence
	}
	return nil
}

func (x *LocalPresence) GetSynchronizedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SynchronizedAt
	}
	return nil
}

func (x *LocalPresence) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

var File_ourspace_firmware_proto_api_proto protoreflect.FileDescriptor

const file_ourspace_firmware_proto_api_proto_rawDesc = "" +
	"\n" +
	"!ourspace-firmware/proto/api.proto\x12\x14ourspace_firmware.v1\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a ourspace-backend/proto/api.proto\"3\n" +
	"\x0fScanCardRequest\x12 \n" +
	"\vcard_serial\x18\x01 \x01(\tR\vcard_serial\",\n" +
	"\x10ScanCardResponse\x12\x18\n" +
	"\aoutcome\x18\x01 \x01(\tR\aoutcome\"\x1c\n" +
	"\x1aListenForCardEventsRequest\"\xd7\x01\n" +
	"\x1bListenForCardEventsResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12.\n" +
	"\x04card\x18\x02 \x01(\v2\x1a.ourspace_firmware.v1.CardR\x04card\x124\n" +
	"\x06member\x18\x03 \x01(\v2\x1c.ourspace_firmware.v1.MemberR\x06member\x12<\n" +
	"\bpresence\x18\x04 \x01(\v2 .ourspace_backend.proto.PresenceR\bpresence\",\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8a\x01\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12:\n" +
	"\n" +
	"valid_from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"valid_from\x126\n" +
	"\bvalid_to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bvalid_to\"\xcf\x01\n" +
	"\rLocalPresence\x12<\n" +
	"\bpresence\x18\x01 \x01(\v2 .ourspace_backend.proto.PresenceR\bpresence\x12C\n" +
	"\x0fsynchronized_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0esynchronizedAt\x12;\n" +
	"\vmodified_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt2\x81\x02\n" +
	"\x0fFirmwareService\x12n\n" +
	"\bScanCard\x12%.ourspace_firmware.v1.ScanCardRequest\x1a&.ourspace_firmware.v1.ScanCardResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/card\x12~\n" +
	"\x13ListenForCardEvents\x120.ourspace_firmware.v1.ListenForCardEventsRequest\x1a1.ourspace_firmware.v1.ListenForCardEventsResponse\"\x000\x01B\xab\x01\xbaGr\x12J\n" +
	"\x15ourspace-firmware-api\x12,Local API for the Terminal frontend firmware2\x031.0\x1a$\n" +
	"\x15http://localhost:8080\x12\vHost ServerZ4github.com/cfhn/our-space/ourspace-firmware/proto;pbX\x00b\x06proto3"

var (
	file_ourspace_firmware_proto_api_proto_rawDescOnce sync.Once
	file_ourspace_firmware_proto_api_proto_rawDescData []byte
)

func file_ourspace_firmware_proto_api_proto_rawDescGZIP() []byte {
	file_ourspace_firmware_proto_api_proto_rawDescOnce.Do(func() {
		file_ourspace_firmware_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ourspace_firmware_proto_api_proto_rawDesc), len(file_ourspace_firmware_proto_api_proto_rawDesc)))
	})
	return file_ourspace_firmware_proto_api_proto_rawDescData
}

var file_ourspace_firmware_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ourspace_firmware_proto_api_proto_goTypes = []any{
	(*ScanCardRequest)(nil),             // 0: ourspace_firmware.v1.ScanCardRequest
	(*ScanCardResponse)(nil),            // 1: ourspace_firmware.v1.ScanCardResponse
	(*ListenForCardEventsRequest)(nil),  // 2: ourspace_firmware.v1.ListenForCardEventsRequest
	(*ListenForCardEventsResponse)(nil), // 3: ourspace_firmware.v1.ListenForCardEventsResponse
	(*Member)(nil),                      // 4: ourspace_firmware.v1.Member
	(*Card)(nil),                        // 5: ourspace_firmware.v1.Card
	(*LocalPresence)(nil),               // 6: ourspace_firmware.v1.LocalPresence
	(*proto.Presence)(nil),              // 7: ourspace_backend.proto.Presence
	(*timestamppb.Timestamp)(nil),       // 8: google.protobuf.Timestamp
}
var file_ourspace_firmware_proto_api_proto_depIdxs = []int32{
	5,  // 0: ourspace_firmware.v1.ListenForCardEventsResponse.card:type_name -> ourspace_firmware.v1.Card
	4,  // 1: ourspace_firmware.v1.ListenForCardEventsResponse.member:type_name -> ourspace_firmware.v1.Member
	7,  // 2: ourspace_firmware.v1.ListenForCardEventsResponse.presence:type_name -> ourspace_backend.proto.Presence
	8,  // 3: ourspace_firmware.v1.Card.valid_from:type_name -> google.protobuf.Timestamp
	8,  // 4: ourspace_firmware.v1.Card.valid_to:type_name -> google.protobuf.Timestamp
	7,  // 5: ourspace_firmware.v1.LocalPresence.presence:type_name -> ourspace_backend.proto.Presence
	8,  // 6: ourspace_firmware.v1.LocalPresence.synchronized_at:type_name -> google.protobuf.Timestamp
	8,  // 7: ourspace_firmware.v1.LocalPresence.modified_at:type_name -> google.protobuf.Timestamp
	0,  // 8: ourspace_firmware.v1.FirmwareService.ScanCard:input_type -> ourspace_firmware.v1.ScanCardRequest
	2,  // 9: ourspace_firmware.v1.FirmwareService.ListenForCardEvents:input_type -> ourspace_firmware.v1.ListenForCardEventsRequest
	1,  // 10: ourspace_firmware.v1.FirmwareService.ScanCard:output_type -> ourspace_firmware.v1.ScanCardResponse
	3,  // 11: ourspace_firmware.v1.FirmwareService.ListenForCardEvents:output_type -> ourspace_firmware.v1.ListenForCardEventsResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_ourspace_firmware_proto_api_proto_init() }
func file_ourspace_firmware_proto_api_proto_init() {
	if File_ourspace_firmware_proto_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ourspace_firmware_proto_api_proto_rawDesc), len(file_ourspace_firmware_proto_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ourspace_firmware_proto_api_proto_goTypes,
		DependencyIndexes: file_ourspace_firmware_proto_api_proto_depIdxs,
		MessageInfos:      file_ourspace_firmware_proto_api_proto_msgTypes,
	}.Build()
	File_ourspace_firmware_proto_api_proto = out.File
	file_ourspace_firmware_proto_api_proto_goTypes = nil
	file_ourspace_firmware_proto_api_proto_depIdxs = nil
}
