// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api.proto

package pb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Member        *Member                `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemberRequest) Reset() {
	*x = CreateMemberRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemberRequest) ProtoMessage() {}

func (x *CreateMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemberRequest.ProtoReflect.Descriptor instead.
func (*CreateMemberRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMemberRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *CreateMemberRequest) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type Member struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MembershipStart *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=membership_start,json=membershipStart,proto3" json:"membership_start,omitempty"`
	MembershipEnd   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=membership_end,json=membershipEnd,proto3" json:"membership_end,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Member) GetMembershipStart() *timestamppb.Timestamp {
	if x != nil {
		return x.MembershipStart
	}
	return nil
}

func (x *Member) GetMembershipEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.MembershipEnd
	}
	return nil
}

type GetMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberRequest) Reset() {
	*x = GetMemberRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberRequest) ProtoMessage() {}

func (x *GetMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberRequest.ProtoReflect.Descriptor instead.
func (*GetMemberRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetMemberRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *ListMembersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMembersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *ListMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListMembersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type PageToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageToken) Reset() {
	*x = PageToken{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageToken) ProtoMessage() {}

func (x *PageToken) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageToken.ProtoReflect.Descriptor instead.
func (*PageToken) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

type UpdateMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRequest) Reset() {
	*x = UpdateMemberRequest{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRequest) ProtoMessage() {}

func (x *UpdateMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMemberRequest) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *UpdateMemberRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

type DeleteMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemberRequest) Reset() {
	*x = DeleteMemberRequest{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemberRequest) ProtoMessage() {}

func (x *DeleteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemberRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemberRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMemberRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	RfidValue     []byte                 `protobuf:"bytes,3,opt,name=rfid_value,json=rfidValue,proto3" json:"rfid_value,omitempty"`
	ValidFrom     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *Card) GetRfidValue() []byte {
	if x != nil {
		return x.RfidValue
	}
	return nil
}

func (x *Card) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *Card) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

type CreateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Card          *Card                  `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *CreateCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CreateCardRequest) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type GetCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardRequest) Reset() {
	*x = GetCardRequest{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardRequest) ProtoMessage() {}

func (x *GetCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardRequest.ProtoReflect.Descriptor instead.
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsRequest) Reset() {
	*x = ListCardsRequest{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsRequest) ProtoMessage() {}

func (x *ListCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsRequest.ProtoReflect.Descriptor instead.
func (*ListCardsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *ListCardsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCardsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsResponse) Reset() {
	*x = ListCardsResponse{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsResponse) ProtoMessage() {}

func (x *ListCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsResponse.ProtoReflect.Descriptor instead.
func (*ListCardsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *ListCardsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *ListCardsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardRequest) Reset() {
	*x = UpdateCardRequest{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardRequest) ProtoMessage() {}

func (x *UpdateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateCardRequest) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *UpdateCardRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

type DeleteCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardRequest) Reset() {
	*x = DeleteCardRequest{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardRequest) ProtoMessage() {}

func (x *DeleteCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BriefingType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ExpiresAfter  *durationpb.Duration   `protobuf:"bytes,4,opt,name=expires_after,json=expiresAfter,proto3" json:"expires_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BriefingType) Reset() {
	*x = BriefingType{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BriefingType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BriefingType) ProtoMessage() {}

func (x *BriefingType) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BriefingType.ProtoReflect.Descriptor instead.
func (*BriefingType) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *BriefingType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BriefingType) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *BriefingType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BriefingType) GetExpiresAfter() *durationpb.Duration {
	if x != nil {
		return x.ExpiresAfter
	}
	return nil
}

type CreateBriefingTypeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BriefingTypeId string                 `protobuf:"bytes,1,opt,name=briefing_type_id,json=briefingTypeId,proto3" json:"briefing_type_id,omitempty"`
	BriefingType   *BriefingType          `protobuf:"bytes,2,opt,name=briefing_type,json=briefingType,proto3" json:"briefing_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateBriefingTypeRequest) Reset() {
	*x = CreateBriefingTypeRequest{}
	mi := &file_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBriefingTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBriefingTypeRequest) ProtoMessage() {}

func (x *CreateBriefingTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBriefingTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateBriefingTypeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

func (x *CreateBriefingTypeRequest) GetBriefingTypeId() string {
	if x != nil {
		return x.BriefingTypeId
	}
	return ""
}

func (x *CreateBriefingTypeRequest) GetBriefingType() *BriefingType {
	if x != nil {
		return x.BriefingType
	}
	return nil
}

type GetBriefingTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBriefingTypeRequest) Reset() {
	*x = GetBriefingTypeRequest{}
	mi := &file_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBriefingTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBriefingTypeRequest) ProtoMessage() {}

func (x *GetBriefingTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBriefingTypeRequest.ProtoReflect.Descriptor instead.
func (*GetBriefingTypeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

func (x *GetBriefingTypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListBriefingTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBriefingTypesRequest) Reset() {
	*x = ListBriefingTypesRequest{}
	mi := &file_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBriefingTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBriefingTypesRequest) ProtoMessage() {}

func (x *ListBriefingTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBriefingTypesRequest.ProtoReflect.Descriptor instead.
func (*ListBriefingTypesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{18}
}

func (x *ListBriefingTypesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListBriefingTypesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListBriefingTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BriefingTypes []*BriefingType        `protobuf:"bytes,1,rep,name=briefing_types,json=briefingTypes,proto3" json:"briefing_types,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBriefingTypesResponse) Reset() {
	*x = ListBriefingTypesResponse{}
	mi := &file_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBriefingTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBriefingTypesResponse) ProtoMessage() {}

func (x *ListBriefingTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBriefingTypesResponse.ProtoReflect.Descriptor instead.
func (*ListBriefingTypesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{19}
}

func (x *ListBriefingTypesResponse) GetBriefingTypes() []*BriefingType {
	if x != nil {
		return x.BriefingTypes
	}
	return nil
}

func (x *ListBriefingTypesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateBriefingTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BriefingType  *BriefingType          `protobuf:"bytes,1,opt,name=briefing_type,json=briefingType,proto3" json:"briefing_type,omitempty"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBriefingTypeRequest) Reset() {
	*x = UpdateBriefingTypeRequest{}
	mi := &file_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBriefingTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBriefingTypeRequest) ProtoMessage() {}

func (x *UpdateBriefingTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBriefingTypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateBriefingTypeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateBriefingTypeRequest) GetBriefingType() *BriefingType {
	if x != nil {
		return x.BriefingType
	}
	return nil
}

func (x *UpdateBriefingTypeRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

type DeleteBriefingTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBriefingTypeRequest) Reset() {
	*x = DeleteBriefingTypeRequest{}
	mi := &file_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBriefingTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBriefingTypeRequest) ProtoMessage() {}

func (x *DeleteBriefingTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBriefingTypeRequest.ProtoReflect.Descriptor instead.
func (*DeleteBriefingTypeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteBriefingTypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Briefing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BriefingType  string                 `protobuf:"bytes,2,opt,name=briefing_type,json=briefingType,proto3" json:"briefing_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Briefing) Reset() {
	*x = Briefing{}
	mi := &file_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Briefing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Briefing) ProtoMessage() {}

func (x *Briefing) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Briefing.ProtoReflect.Descriptor instead.
func (*Briefing) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{22}
}

func (x *Briefing) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Briefing) GetBriefingType() string {
	if x != nil {
		return x.BriefingType
	}
	return ""
}

type CreateBriefingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BriefingId    string                 `protobuf:"bytes,1,opt,name=briefing_id,json=briefingId,proto3" json:"briefing_id,omitempty"`
	Briefing      *Briefing              `protobuf:"bytes,2,opt,name=briefing,proto3" json:"briefing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBriefingRequest) Reset() {
	*x = CreateBriefingRequest{}
	mi := &file_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBriefingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBriefingRequest) ProtoMessage() {}

func (x *CreateBriefingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBriefingRequest.ProtoReflect.Descriptor instead.
func (*CreateBriefingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{23}
}

func (x *CreateBriefingRequest) GetBriefingId() string {
	if x != nil {
		return x.BriefingId
	}
	return ""
}

func (x *CreateBriefingRequest) GetBriefing() *Briefing {
	if x != nil {
		return x.Briefing
	}
	return nil
}

type GetBriefingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBriefingRequest) Reset() {
	*x = GetBriefingRequest{}
	mi := &file_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBriefingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBriefingRequest) ProtoMessage() {}

func (x *GetBriefingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBriefingRequest.ProtoReflect.Descriptor instead.
func (*GetBriefingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{24}
}

func (x *GetBriefingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListBriefingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBriefingsRequest) Reset() {
	*x = ListBriefingsRequest{}
	mi := &file_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBriefingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBriefingsRequest) ProtoMessage() {}

func (x *ListBriefingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBriefingsRequest.ProtoReflect.Descriptor instead.
func (*ListBriefingsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{25}
}

func (x *ListBriefingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListBriefingsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListBriefingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Briefings     []*Briefing            `protobuf:"bytes,1,rep,name=briefings,proto3" json:"briefings,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBriefingsResponse) Reset() {
	*x = ListBriefingsResponse{}
	mi := &file_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBriefingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBriefingsResponse) ProtoMessage() {}

func (x *ListBriefingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBriefingsResponse.ProtoReflect.Descriptor instead.
func (*ListBriefingsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{26}
}

func (x *ListBriefingsResponse) GetBriefings() []*Briefing {
	if x != nil {
		return x.Briefings
	}
	return nil
}

func (x *ListBriefingsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateBriefingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Briefing      *Briefing              `protobuf:"bytes,1,opt,name=briefing,proto3" json:"briefing,omitempty"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBriefingRequest) Reset() {
	*x = UpdateBriefingRequest{}
	mi := &file_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBriefingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBriefingRequest) ProtoMessage() {}

func (x *UpdateBriefingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBriefingRequest.ProtoReflect.Descriptor instead.
func (*UpdateBriefingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateBriefingRequest) GetBriefing() *Briefing {
	if x != nil {
		return x.Briefing
	}
	return nil
}

func (x *UpdateBriefingRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

type DeleteBriefingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBriefingRequest) Reset() {
	*x = DeleteBriefingRequest{}
	mi := &file_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBriefingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBriefingRequest) ProtoMessage() {}

func (x *DeleteBriefingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBriefingRequest.ProtoReflect.Descriptor instead.
func (*DeleteBriefingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteBriefingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Presence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	CheckinTime   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=checkin_time,json=checkinTime,proto3" json:"checkin_time,omitempty"`
	CheckoutTime  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=checkout_time,json=checkoutTime,proto3" json:"checkout_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Presence) Reset() {
	*x = Presence{}
	mi := &file_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Presence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Presence) ProtoMessage() {}

func (x *Presence) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Presence.ProtoReflect.Descriptor instead.
func (*Presence) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{29}
}

func (x *Presence) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Presence) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *Presence) GetCheckinTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckinTime
	}
	return nil
}

func (x *Presence) GetCheckoutTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckoutTime
	}
	return nil
}

type ListPrecensesRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PageSize  int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Filters
	MemberId           *string                `protobuf:"bytes,3,opt,name=member_id,json=memberId,proto3,oneof" json:"member_id,omitempty"`
	CheckinTimeAfter   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=checkin_time_after,json=checkinTimeAfter,proto3,oneof" json:"checkin_time_after,omitempty"`
	CheckinTimeBefore  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=checkin_time_before,json=checkinTimeBefore,proto3,oneof" json:"checkin_time_before,omitempty"`
	CheckoutTimeAfter  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=checkout_time_after,json=checkoutTimeAfter,proto3,oneof" json:"checkout_time_after,omitempty"`
	CheckoutTimeBefore *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=checkout_time_before,json=checkoutTimeBefore,proto3,oneof" json:"checkout_time_before,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListPrecensesRequest) Reset() {
	*x = ListPrecensesRequest{}
	mi := &file_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrecensesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrecensesRequest) ProtoMessage() {}

func (x *ListPrecensesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrecensesRequest.ProtoReflect.Descriptor instead.
func (*ListPrecensesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{30}
}

func (x *ListPrecensesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPrecensesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListPrecensesRequest) GetMemberId() string {
	if x != nil && x.MemberId != nil {
		return *x.MemberId
	}
	return ""
}

func (x *ListPrecensesRequest) GetCheckinTimeAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckinTimeAfter
	}
	return nil
}

func (x *ListPrecensesRequest) GetCheckinTimeBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckinTimeBefore
	}
	return nil
}

func (x *ListPrecensesRequest) GetCheckoutTimeAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckoutTimeAfter
	}
	return nil
}

func (x *ListPrecensesRequest) GetCheckoutTimeBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckoutTimeBefore
	}
	return nil
}

type ListPrecensesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presence      []*Presence            `protobuf:"bytes,1,rep,name=presence,proto3" json:"presence,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrecensesResponse) Reset() {
	*x = ListPrecensesResponse{}
	mi := &file_api_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrecensesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrecensesResponse) ProtoMessage() {}

func (x *ListPrecensesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrecensesResponse.ProtoReflect.Descriptor instead.
func (*ListPrecensesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{31}
}

func (x *ListPrecensesResponse) GetPresence() []*Presence {
	if x != nil {
		return x.Presence
	}
	return nil
}

func (x *ListPrecensesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CheckinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckinRequest) Reset() {
	*x = CheckinRequest{}
	mi := &file_api_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckinRequest) ProtoMessage() {}

func (x *CheckinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckinRequest.ProtoReflect.Descriptor instead.
func (*CheckinRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{32}
}

func (x *CheckinRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type CheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_api_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{33}
}

func (x *CheckoutRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type UpdatePresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presence      *Presence              `protobuf:"bytes,1,opt,name=presence,proto3" json:"presence,omitempty"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePresenceRequest) Reset() {
	*x = UpdatePresenceRequest{}
	mi := &file_api_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePresenceRequest) ProtoMessage() {}

func (x *UpdatePresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePresenceRequest.ProtoReflect.Descriptor instead.
func (*UpdatePresenceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{34}
}

func (x *UpdatePresenceRequest) GetPresence() *Presence {
	if x != nil {
		return x.Presence
	}
	return nil
}

func (x *UpdatePresenceRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

type DeletePresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePresenceRequest) Reset() {
	*x = DeletePresenceRequest{}
	mi := &file_api_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePresenceRequest) ProtoMessage() {}

func (x *DeletePresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePresenceRequest.ProtoReflect.Descriptor instead.
func (*DeletePresenceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{35}
}

func (x *DeletePresenceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x13ourspace_backend.v1\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17validate/validate.proto\"g\n" +
	"\x13CreateMemberRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x123\n" +
	"\x06member\x18\x02 \x01(\v2\x1b.ourspace_backend.v1.MemberR\x06member\"\xb6\x01\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12E\n" +
	"\x10membership_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0fmembershipStart\x12A\n" +
	"\x0emembership_end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rmembershipEnd\"\"\n" +
	"\x10GetMemberRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"P\n" +
	"\x12ListMembersRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"t\n" +
	"\x13ListMembersResponse\x125\n" +
	"\amembers\x18\x01 \x03(\v2\x1b.ourspace_backend.v1.MemberR\amembers\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\v\n" +
	"\tPageToken\"\x85\x01\n" +
	"\x13UpdateMemberRequest\x123\n" +
	"\x06member\x18\x01 \x01(\v2\x1b.ourspace_backend.v1.MemberR\x06member\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"%\n" +
	"\x13DeleteMemberRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc4\x01\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12\x1d\n" +
	"\n" +
	"rfid_value\x18\x03 \x01(\fR\trfidValue\x129\n" +
	"\n" +
	"valid_from\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x125\n" +
	"\bvalid_to\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\avalidTo\"[\n" +
	"\x11CreateCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12-\n" +
	"\x04card\x18\x02 \x01(\v2\x19.ourspace_backend.v1.CardR\x04card\" \n" +
	"\x0eGetCardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"N\n" +
	"\x10ListCardsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"l\n" +
	"\x11ListCardsResponse\x12/\n" +
	"\x05cards\x18\x01 \x03(\v2\x19.ourspace_backend.v1.CardR\x05cards\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"}\n" +
	"\x11UpdateCardRequest\x12-\n" +
	"\x04card\x18\x01 \x01(\v2\x19.ourspace_backend.v1.CardR\x04card\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"#\n" +
	"\x11DeleteCardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa3\x01\n" +
	"\fBriefingType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12>\n" +
	"\rexpires_after\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fexpiresAfter\"\x8d\x01\n" +
	"\x19CreateBriefingTypeRequest\x12(\n" +
	"\x10briefing_type_id\x18\x01 \x01(\tR\x0ebriefingTypeId\x12F\n" +
	"\rbriefing_type\x18\x02 \x01(\v2!.ourspace_backend.v1.BriefingTypeR\fbriefingType\"(\n" +
	"\x16GetBriefingTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"V\n" +
	"\x18ListBriefingTypesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x8d\x01\n" +
	"\x19ListBriefingTypesResponse\x12H\n" +
	"\x0ebriefing_types\x18\x01 \x03(\v2!.ourspace_backend.v1.BriefingTypeR\rbriefingTypes\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x9e\x01\n" +
	"\x19UpdateBriefingTypeRequest\x12F\n" +
	"\rbriefing_type\x18\x01 \x01(\v2!.ourspace_backend.v1.BriefingTypeR\fbriefingType\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"+\n" +
	"\x19DeleteBriefingTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\bBriefing\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rbriefing_type\x18\x02 \x01(\tR\fbriefingType\"s\n" +
	"\x15CreateBriefingRequest\x12\x1f\n" +
	"\vbriefing_id\x18\x01 \x01(\tR\n" +
	"briefingId\x129\n" +
	"\bbriefing\x18\x02 \x01(\v2\x1d.ourspace_backend.v1.BriefingR\bbriefing\"$\n" +
	"\x12GetBriefingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x14ListBriefingsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"|\n" +
	"\x15ListBriefingsResponse\x12;\n" +
	"\tbriefings\x18\x01 \x03(\v2\x1d.ourspace_backend.v1.BriefingR\tbriefings\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x8d\x01\n" +
	"\x15UpdateBriefingRequest\x129\n" +
	"\bbriefing\x18\x01 \x01(\v2\x1d.ourspace_backend.v1.BriefingR\bbriefing\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"'\n" +
	"\x15DeleteBriefingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb7\x01\n" +
	"\bPresence\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12=\n" +
	"\fcheckin_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcheckinTime\x12?\n" +
	"\rcheckout_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fcheckoutTime\"\xa6\x04\n" +
	"\x14ListPrecensesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12 \n" +
	"\tmember_id\x18\x03 \x01(\tH\x00R\bmemberId\x88\x01\x01\x12M\n" +
	"\x12checkin_time_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x10checkinTimeAfter\x88\x01\x01\x12O\n" +
	"\x13checkin_time_before\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x11checkinTimeBefore\x88\x01\x01\x12O\n" +
	"\x13checkout_time_after\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x11checkoutTimeAfter\x88\x01\x01\x12Q\n" +
	"\x14checkout_time_before\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x04R\x12checkoutTimeBefore\x88\x01\x01B\f\n" +
	"\n" +
	"_member_idB\x15\n" +
	"\x13_checkin_time_afterB\x16\n" +
	"\x14_checkin_time_beforeB\x16\n" +
	"\x14_checkout_time_afterB\x17\n" +
	"\x15_checkout_time_before\"z\n" +
	"\x15ListPrecensesResponse\x129\n" +
	"\bpresence\x18\x01 \x03(\v2\x1d.ourspace_backend.v1.PresenceR\bpresence\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"-\n" +
	"\x0eCheckinRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\".\n" +
	"\x0fCheckoutRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\"\x8d\x01\n" +
	"\x15UpdatePresenceRequest\x129\n" +
	"\bpresence\x18\x01 \x01(\v2\x1d.ourspace_backend.v1.PresenceR\bpresence\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"'\n" +
	"\x15DeletePresenceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xe4\x06\n" +
	"\rMemberService\x12\xa2\x01\n" +
	"\fCreateMember\x12(.ourspace_backend.v1.CreateMemberRequest\x1a\x1b.ourspace_backend.v1.Member\"K\xbaG-\n" +
	"\aMembers\x12\rCreate Member\x1a\x13Create Space Member\x82\xd3\xe4\x93\x02\x15:\x06member\"\v/v1/members\x12\x99\x01\n" +
	"\tGetMember\x12%.ourspace_backend.v1.GetMemberRequest\x1a\x1b.ourspace_backend.v1.Member\"H\xbaG-\n" +
	"\aMembers\x12\n" +
	"Get member\x1a\x16Get member information\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/members/{id}\x12\xac\x01\n" +
	"\vListMembers\x12'.ourspace_backend.v1.ListMembersRequest\x1a(.ourspace_backend.v1.ListMembersResponse\"J\xbaG4\n" +
	"\aMembers\x12\fList members\x1a\x1bList all registered members\x82\xd3\xe4\x93\x02\r\x12\v/v1/members\x12\xbd\x01\n" +
	"\fUpdateMember\x12(.ourspace_backend.v1.UpdateMemberRequest\x1a\x1b.ourspace_backend.v1.Member\"f\xbaG<\n" +
	"\aMembers\x12\rUpdate member\x1a\"Update specified fields of members\x82\xd3\xe4\x93\x02!:\x06member2\x17/v1/members/{member.id}\x12\xa2\x01\n" +
	"\fDeleteMember\x12(.ourspace_backend.v1.DeleteMemberRequest\x1a\x16.google.protobuf.Empty\"P\xbaG5\n" +
	"\aMembers\x12\rDelete member\x1a\x1bDelete the specified member\x82\xd3\xe4\x93\x02\x12*\x10/v1/members/{id}2\x98\x06\n" +
	"\vCardService\x12\x92\x01\n" +
	"\n" +
	"CreateCard\x12&.ourspace_backend.v1.CreateCardRequest\x1a\x19.ourspace_backend.v1.Card\"A\xbaG'\n" +
	"\x05Cards\x12\vCreate Card\x1a\x11Create Space Card\x82\xd3\xe4\x93\x02\x11:\x04card\"\t/v1/cards\x12\x8b\x01\n" +
	"\aGetCard\x12#.ourspace_backend.v1.GetCardRequest\x1a\x19.ourspace_backend.v1.Card\"@\xbaG'\n" +
	"\x05Cards\x12\bGet card\x1a\x14Get card information\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/cards/{id}\x12\x9e\x01\n" +
	"\tListCards\x12%.ourspace_backend.v1.ListCardsRequest\x1a&.ourspace_backend.v1.ListCardsResponse\"B\xbaG.\n" +
	"\x05Cards\x12\n" +
	"List cards\x1a\x19List all registered cards\x82\xd3\xe4\x93\x02\v\x12\t/v1/cards\x12\xab\x01\n" +
	"\n" +
	"UpdateCard\x12&.ourspace_backend.v1.UpdateCardRequest\x1a\x19.ourspace_backend.v1.Card\"Z\xbaG6\n" +
	"\x05Cards\x12\vUpdate card\x1a Update specified fields of cards\x82\xd3\xe4\x93\x02\x1b:\x04card2\x13/v1/cards/{card.id}\x12\x96\x01\n" +
	"\n" +
	"DeleteCard\x12&.ourspace_backend.v1.DeleteCardRequest\x1a\x16.google.protobuf.Empty\"H\xbaG/\n" +
	"\x05Cards\x12\vDelete card\x1a\x19Delete the specified card\x82\xd3\xe4\x93\x02\x10*\x0e/v1/cards/{id}2\xf8\x0f\n" +
	"\x0fBriefingService\x12\xb3\x01\n" +
	"\x0eCreateBriefing\x12*.ourspace_backend.v1.CreateBriefingRequest\x1a\x1d.ourspace_backend.v1.Briefing\"V\xbaG4\n" +
	"\tBriefings\x12\x0fCreate Briefing\x1a\x16Create safety briefing\x82\xd3\xe4\x93\x02\x19:\bbriefing\"\r/v1/briefings\x12\xa7\x01\n" +
	"\vGetBriefing\x12'.ourspace_backend.v1.GetBriefingRequest\x1a\x1d.ourspace_backend.v1.Briefing\"P\xbaG3\n" +
	"\tBriefings\x12\fGet briefing\x1a\x18Get briefing information\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/briefings/{id}\x12\xba\x01\n" +
	"\rListBriefings\x12).ourspace_backend.v1.ListBriefingsRequest\x1a*.ourspace_backend.v1.ListBriefingsResponse\"R\xbaG:\n" +
	"\tBriefings\x12\x0eList briefings\x1a\x1dList all registered briefings\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/briefings\x12\xcf\x01\n" +
	"\x0eUpdateBriefing\x12*.ourspace_backend.v1.UpdateBriefingRequest\x1a\x1d.ourspace_backend.v1.Briefing\"r\xbaGB\n" +
	"\tBriefings\x12\x0fUpdate briefing\x1a$Update specified fields of briefings\x82\xd3\xe4\x93\x02':\bbriefing2\x1b/v1/briefings/{briefing.id}\x12\xae\x01\n" +
	"\x0eDeleteBriefing\x12*.ourspace_backend.v1.DeleteBriefingRequest\x1a\x16.google.protobuf.Empty\"X\xbaG;\n" +
	"\tBriefings\x12\x0fDelete briefing\x1a\x1dDelete the specified briefing\x82\xd3\xe4\x93\x02\x14*\x12/v1/briefings/{id}\x12\xd7\x01\n" +
	"\x12CreateBriefingType\x12..ourspace_backend.v1.CreateBriefingTypeRequest\x1a!.ourspace_backend.v1.BriefingType\"n\xbaGB\n" +
	"\rBriefingTypes\x12\x14Create briefing type\x1a\x1bCreate safety briefing type\x82\xd3\xe4\x93\x02#:\rbriefing_type\"\x12/v1/briefing-types\x12\xc6\x01\n" +
	"\x0fGetBriefingType\x12+.ourspace_backend.v1.GetBriefingTypeRequest\x1a!.ourspace_backend.v1.BriefingType\"c\xbaGA\n" +
	"\rBriefingTypes\x12\x11Get briefing-type\x1a\x1dGet briefing type information\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/briefing-types/{id}\x12\xd9\x01\n" +
	"\x11ListBriefingTypes\x12-.ourspace_backend.v1.ListBriefingTypesRequest\x1a..ourspace_backend.v1.ListBriefingTypesResponse\"e\xbaGH\n" +
	"\rBriefingTypes\x12\x13List briefing types\x1a\"List all registered briefing types\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/briefing-types\x12\xf9\x01\n" +
	"\x12UpdateBriefingType\x12..ourspace_backend.v1.UpdateBriefingTypeRequest\x1a!.ourspace_backend.v1.BriefingType\"\x8f\x01\xbaGP\n" +
	"\rBriefingTypes\x12\x14Update briefing type\x1a)Update specified fields of briefing types\x82\xd3\xe4\x93\x026:\rbriefing_type2%/v1/briefing-types/{briefing_type.id}\x12\xc9\x01\n" +
	"\x12DeleteBriefingType\x12..ourspace_backend.v1.DeleteBriefingTypeRequest\x1a\x16.google.protobuf.Empty\"k\xbaGI\n" +
	"\rBriefingTypes\x12\x14Delete briefing-type\x1a\"Delete the specified briefing type\x82\xd3\xe4\x93\x02\x19*\x17/v1/briefing-types/{id}2\x94\b\n" +
	"\x0fPresenceService\x12\xce\x01\n" +
	"\rListPresences\x12).ourspace_backend.v1.ListPrecensesRequest\x1a*.ourspace_backend.v1.ListPrecensesResponse\"f\xbaGN\n" +
	"\tPresences\x12\x0eList presences\x1a1List precenses, where members have checked in/out\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/presences\x12\xb7\x01\n" +
	"\aCheckin\x12#.ourspace_backend.v1.CheckinRequest\x1a\x1d.ourspace_backend.v1.Presence\"h\xbaGE\n" +
	"\tPresences\x12\bCheck in\x1a.Check in a member, this creates a new presence\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/presences:checkin\x12\xc6\x01\n" +
	"\bCheckout\x12$.ourspace_backend.v1.CheckoutRequest\x1a\x1d.ourspace_backend.v1.Presence\"u\xbaGQ\n" +
	"\tPresences\x12\tCheck out\x1a9Check out a member, ends an open presence if there is one\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/presences:checkout\x12\x80\x02\n" +
	"\x0eUpdatePresence\x12*.ourspace_backend.v1.UpdatePresenceRequest\x1a\x1d.ourspace_backend.v1.Presence\"\xa2\x01\xbaGr\n" +
	"\tPresences\x12\x0fUpdate presence\x1aTUpdates a presence. Usual operation should be via checkin/checkout instead of update\x82\xd3\xe4\x93\x02':\bpresence\"\x1b/v1/presences/{presence.id}\x12\xa9\x01\n" +
	"\x0eDeletePresence\x12*.ourspace_backend.v1.DeletePresenceRequest\x1a\x16.google.protobuf.Empty\"S\xbaG6\n" +
	"\tPresences\x12\x0fDelete Presence\x1a\x18Delete a presence record\x82\xd3\xe4\x93\x02\x14\"\x12/v1/presences/{id}B\xb2\x01\xbaG}\x12U\n" +
	"\x14ourspace-backend-api\x128Manage members and their qualifications for Maker Spaces2\x031.0\x1a$\n" +
	"\x15http://localhost:8080\x12\vHost ServerZ0github.com/cfhn/our-space/ourspace-backend/pb;pbX\x00b\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_api_proto_goTypes = []any{
	(*CreateMemberRequest)(nil),       // 0: ourspace_backend.v1.CreateMemberRequest
	(*Member)(nil),                    // 1: ourspace_backend.v1.Member
	(*GetMemberRequest)(nil),          // 2: ourspace_backend.v1.GetMemberRequest
	(*ListMembersRequest)(nil),        // 3: ourspace_backend.v1.ListMembersRequest
	(*ListMembersResponse)(nil),       // 4: ourspace_backend.v1.ListMembersResponse
	(*PageToken)(nil),                 // 5: ourspace_backend.v1.PageToken
	(*UpdateMemberRequest)(nil),       // 6: ourspace_backend.v1.UpdateMemberRequest
	(*DeleteMemberRequest)(nil),       // 7: ourspace_backend.v1.DeleteMemberRequest
	(*Card)(nil),                      // 8: ourspace_backend.v1.Card
	(*CreateCardRequest)(nil),         // 9: ourspace_backend.v1.CreateCardRequest
	(*GetCardRequest)(nil),            // 10: ourspace_backend.v1.GetCardRequest
	(*ListCardsRequest)(nil),          // 11: ourspace_backend.v1.ListCardsRequest
	(*ListCardsResponse)(nil),         // 12: ourspace_backend.v1.ListCardsResponse
	(*UpdateCardRequest)(nil),         // 13: ourspace_backend.v1.UpdateCardRequest
	(*DeleteCardRequest)(nil),         // 14: ourspace_backend.v1.DeleteCardRequest
	(*BriefingType)(nil),              // 15: ourspace_backend.v1.BriefingType
	(*CreateBriefingTypeRequest)(nil), // 16: ourspace_backend.v1.CreateBriefingTypeRequest
	(*GetBriefingTypeRequest)(nil),    // 17: ourspace_backend.v1.GetBriefingTypeRequest
	(*ListBriefingTypesRequest)(nil),  // 18: ourspace_backend.v1.ListBriefingTypesRequest
	(*ListBriefingTypesResponse)(nil), // 19: ourspace_backend.v1.ListBriefingTypesResponse
	(*UpdateBriefingTypeRequest)(nil), // 20: ourspace_backend.v1.UpdateBriefingTypeRequest
	(*DeleteBriefingTypeRequest)(nil), // 21: ourspace_backend.v1.DeleteBriefingTypeRequest
	(*Briefing)(nil),                  // 22: ourspace_backend.v1.Briefing
	(*CreateBriefingRequest)(nil),     // 23: ourspace_backend.v1.CreateBriefingRequest
	(*GetBriefingRequest)(nil),        // 24: ourspace_backend.v1.GetBriefingRequest
	(*ListBriefingsRequest)(nil),      // 25: ourspace_backend.v1.ListBriefingsRequest
	(*ListBriefingsResponse)(nil),     // 26: ourspace_backend.v1.ListBriefingsResponse
	(*UpdateBriefingRequest)(nil),     // 27: ourspace_backend.v1.UpdateBriefingRequest
	(*DeleteBriefingRequest)(nil),     // 28: ourspace_backend.v1.DeleteBriefingRequest
	(*Presence)(nil),                  // 29: ourspace_backend.v1.Presence
	(*ListPrecensesRequest)(nil),      // 30: ourspace_backend.v1.ListPrecensesRequest
	(*ListPrecensesResponse)(nil),     // 31: ourspace_backend.v1.ListPrecensesResponse
	(*CheckinRequest)(nil),            // 32: ourspace_backend.v1.CheckinRequest
	(*CheckoutRequest)(nil),           // 33: ourspace_backend.v1.CheckoutRequest
	(*UpdatePresenceRequest)(nil),     // 34: ourspace_backend.v1.UpdatePresenceRequest
	(*DeletePresenceRequest)(nil),     // 35: ourspace_backend.v1.DeletePresenceRequest
	(*timestamppb.Timestamp)(nil),     // 36: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),     // 37: google.protobuf.FieldMask
	(*durationpb.Duration)(nil),       // 38: google.protobuf.Duration
	(*emptypb.Empty)(nil),             // 39: google.protobuf.Empty
}
var file_api_proto_depIdxs = []int32{
	1,  // 0: ourspace_backend.v1.CreateMemberRequest.member:type_name -> ourspace_backend.v1.Member
	36, // 1: ourspace_backend.v1.Member.membership_start:type_name -> google.protobuf.Timestamp
	36, // 2: ourspace_backend.v1.Member.membership_end:type_name -> google.protobuf.Timestamp
	1,  // 3: ourspace_backend.v1.ListMembersResponse.members:type_name -> ourspace_backend.v1.Member
	1,  // 4: ourspace_backend.v1.UpdateMemberRequest.member:type_name -> ourspace_backend.v1.Member
	37, // 5: ourspace_backend.v1.UpdateMemberRequest.field_mask:type_name -> google.protobuf.FieldMask
	36, // 6: ourspace_backend.v1.Card.valid_from:type_name -> google.protobuf.Timestamp
	36, // 7: ourspace_backend.v1.Card.valid_to:type_name -> google.protobuf.Timestamp
	8,  // 8: ourspace_backend.v1.CreateCardRequest.card:type_name -> ourspace_backend.v1.Card
	8,  // 9: ourspace_backend.v1.ListCardsResponse.cards:type_name -> ourspace_backend.v1.Card
	8,  // 10: ourspace_backend.v1.UpdateCardRequest.card:type_name -> ourspace_backend.v1.Card
	37, // 11: ourspace_backend.v1.UpdateCardRequest.field_mask:type_name -> google.protobuf.FieldMask
	38, // 12: ourspace_backend.v1.BriefingType.expires_after:type_name -> google.protobuf.Duration
	15, // 13: ourspace_backend.v1.CreateBriefingTypeRequest.briefing_type:type_name -> ourspace_backend.v1.BriefingType
	15, // 14: ourspace_backend.v1.ListBriefingTypesResponse.briefing_types:type_name -> ourspace_backend.v1.BriefingType
	15, // 15: ourspace_backend.v1.UpdateBriefingTypeRequest.briefing_type:type_name -> ourspace_backend.v1.BriefingType
	37, // 16: ourspace_backend.v1.UpdateBriefingTypeRequest.field_mask:type_name -> google.protobuf.FieldMask
	22, // 17: ourspace_backend.v1.CreateBriefingRequest.briefing:type_name -> ourspace_backend.v1.Briefing
	22, // 18: ourspace_backend.v1.ListBriefingsResponse.briefings:type_name -> ourspace_backend.v1.Briefing
	22, // 19: ourspace_backend.v1.UpdateBriefingRequest.briefing:type_name -> ourspace_backend.v1.Briefing
	37, // 20: ourspace_backend.v1.UpdateBriefingRequest.field_mask:type_name -> google.protobuf.FieldMask
	36, // 21: ourspace_backend.v1.Presence.checkin_time:type_name -> google.protobuf.Timestamp
	36, // 22: ourspace_backend.v1.Presence.checkout_time:type_name -> google.protobuf.Timestamp
	36, // 23: ourspace_backend.v1.ListPrecensesRequest.checkin_time_after:type_name -> google.protobuf.Timestamp
	36, // 24: ourspace_backend.v1.ListPrecensesRequest.checkin_time_before:type_name -> google.protobuf.Timestamp
	36, // 25: ourspace_backend.v1.ListPrecensesRequest.checkout_time_after:type_name -> google.protobuf.Timestamp
	36, // 26: ourspace_backend.v1.ListPrecensesRequest.checkout_time_before:type_name -> google.protobuf.Timestamp
	29, // 27: ourspace_backend.v1.ListPrecensesResponse.presence:type_name -> ourspace_backend.v1.Presence
	29, // 28: ourspace_backend.v1.UpdatePresenceRequest.presence:type_name -> ourspace_backend.v1.Presence
	37, // 29: ourspace_backend.v1.UpdatePresenceRequest.field_mask:type_name -> google.protobuf.FieldMask
	0,  // 30: ourspace_backend.v1.MemberService.CreateMember:input_type -> ourspace_backend.v1.CreateMemberRequest
	2,  // 31: ourspace_backend.v1.MemberService.GetMember:input_type -> ourspace_backend.v1.GetMemberRequest
	3,  // 32: ourspace_backend.v1.MemberService.ListMembers:input_type -> ourspace_backend.v1.ListMembersRequest
	6,  // 33: ourspace_backend.v1.MemberService.UpdateMember:input_type -> ourspace_backend.v1.UpdateMemberRequest
	7,  // 34: ourspace_backend.v1.MemberService.DeleteMember:input_type -> ourspace_backend.v1.DeleteMemberRequest
	9,  // 35: ourspace_backend.v1.CardService.CreateCard:input_type -> ourspace_backend.v1.CreateCardRequest
	10, // 36: ourspace_backend.v1.CardService.GetCard:input_type -> ourspace_backend.v1.GetCardRequest
	11, // 37: ourspace_backend.v1.CardService.ListCards:input_type -> ourspace_backend.v1.ListCardsRequest
	13, // 38: ourspace_backend.v1.CardService.UpdateCard:input_type -> ourspace_backend.v1.UpdateCardRequest
	14, // 39: ourspace_backend.v1.CardService.DeleteCard:input_type -> ourspace_backend.v1.DeleteCardRequest
	23, // 40: ourspace_backend.v1.BriefingService.CreateBriefing:input_type -> ourspace_backend.v1.CreateBriefingRequest
	24, // 41: ourspace_backend.v1.BriefingService.GetBriefing:input_type -> ourspace_backend.v1.GetBriefingRequest
	25, // 42: ourspace_backend.v1.BriefingService.ListBriefings:input_type -> ourspace_backend.v1.ListBriefingsRequest
	27, // 43: ourspace_backend.v1.BriefingService.UpdateBriefing:input_type -> ourspace_backend.v1.UpdateBriefingRequest
	28, // 44: ourspace_backend.v1.BriefingService.DeleteBriefing:input_type -> ourspace_backend.v1.DeleteBriefingRequest
	16, // 45: ourspace_backend.v1.BriefingService.CreateBriefingType:input_type -> ourspace_backend.v1.CreateBriefingTypeRequest
	17, // 46: ourspace_backend.v1.BriefingService.GetBriefingType:input_type -> ourspace_backend.v1.GetBriefingTypeRequest
	18, // 47: ourspace_backend.v1.BriefingService.ListBriefingTypes:input_type -> ourspace_backend.v1.ListBriefingTypesRequest
	20, // 48: ourspace_backend.v1.BriefingService.UpdateBriefingType:input_type -> ourspace_backend.v1.UpdateBriefingTypeRequest
	21, // 49: ourspace_backend.v1.BriefingService.DeleteBriefingType:input_type -> ourspace_backend.v1.DeleteBriefingTypeRequest
	30, // 50: ourspace_backend.v1.PresenceService.ListPresences:input_type -> ourspace_backend.v1.ListPrecensesRequest
	32, // 51: ourspace_backend.v1.PresenceService.Checkin:input_type -> ourspace_backend.v1.CheckinRequest
	33, // 52: ourspace_backend.v1.PresenceService.Checkout:input_type -> ourspace_backend.v1.CheckoutRequest
	34, // 53: ourspace_backend.v1.PresenceService.UpdatePresence:input_type -> ourspace_backend.v1.UpdatePresenceRequest
	35, // 54: ourspace_backend.v1.PresenceService.DeletePresence:input_type -> ourspace_backend.v1.DeletePresenceRequest
	1,  // 55: ourspace_backend.v1.MemberService.CreateMember:output_type -> ourspace_backend.v1.Member
	1,  // 56: ourspace_backend.v1.MemberService.GetMember:output_type -> ourspace_backend.v1.Member
	4,  // 57: ourspace_backend.v1.MemberService.ListMembers:output_type -> ourspace_backend.v1.ListMembersResponse
	1,  // 58: ourspace_backend.v1.MemberService.UpdateMember:output_type -> ourspace_backend.v1.Member
	39, // 59: ourspace_backend.v1.MemberService.DeleteMember:output_type -> google.protobuf.Empty
	8,  // 60: ourspace_backend.v1.CardService.CreateCard:output_type -> ourspace_backend.v1.Card
	8,  // 61: ourspace_backend.v1.CardService.GetCard:output_type -> ourspace_backend.v1.Card
	12, // 62: ourspace_backend.v1.CardService.ListCards:output_type -> ourspace_backend.v1.ListCardsResponse
	8,  // 63: ourspace_backend.v1.CardService.UpdateCard:output_type -> ourspace_backend.v1.Card
	39, // 64: ourspace_backend.v1.CardService.DeleteCard:output_type -> google.protobuf.Empty
	22, // 65: ourspace_backend.v1.BriefingService.CreateBriefing:output_type -> ourspace_backend.v1.Briefing
	22, // 66: ourspace_backend.v1.BriefingService.GetBriefing:output_type -> ourspace_backend.v1.Briefing
	26, // 67: ourspace_backend.v1.BriefingService.ListBriefings:output_type -> ourspace_backend.v1.ListBriefingsResponse
	22, // 68: ourspace_backend.v1.BriefingService.UpdateBriefing:output_type -> ourspace_backend.v1.Briefing
	39, // 69: ourspace_backend.v1.BriefingService.DeleteBriefing:output_type -> google.protobuf.Empty
	15, // 70: ourspace_backend.v1.BriefingService.CreateBriefingType:output_type -> ourspace_backend.v1.BriefingType
	15, // 71: ourspace_backend.v1.BriefingService.GetBriefingType:output_type -> ourspace_backend.v1.BriefingType
	19, // 72: ourspace_backend.v1.BriefingService.ListBriefingTypes:output_type -> ourspace_backend.v1.ListBriefingTypesResponse
	15, // 73: ourspace_backend.v1.BriefingService.UpdateBriefingType:output_type -> ourspace_backend.v1.BriefingType
	39, // 74: ourspace_backend.v1.BriefingService.DeleteBriefingType:output_type -> google.protobuf.Empty
	31, // 75: ourspace_backend.v1.PresenceService.ListPresences:output_type -> ourspace_backend.v1.ListPrecensesResponse
	29, // 76: ourspace_backend.v1.PresenceService.Checkin:output_type -> ourspace_backend.v1.Presence
	29, // 77: ourspace_backend.v1.PresenceService.Checkout:output_type -> ourspace_backend.v1.Presence
	29, // 78: ourspace_backend.v1.PresenceService.UpdatePresence:output_type -> ourspace_backend.v1.Presence
	39, // 79: ourspace_backend.v1.PresenceService.DeletePresence:output_type -> google.protobuf.Empty
	55, // [55:80] is the sub-list for method output_type
	30, // [30:55] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_api_proto_msgTypes[30].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
